Partner Onboarding/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Onboarding_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Onboarding Template</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Onboarding__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Onboarding__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Partner Onboarding/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Onboarding_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Onboarding Template</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Onboarding__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Onboarding__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Onboarding_Status__c</fullName>
        <inlineHelpText>Holds the current status of the onboarding plan for the contact. Key field to drive business process based on journey status. Use it to trigger notifications, posts, requesting of funds etc.</inlineHelpText>
        <label>Onboarding Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Role_Function__c</fullName>
        <defaultValue>&quot;All&quot;</defaultValue>
        <description>When defining a partner contact, use these values to broadly identify the contact&apos;s function. Field used to generate onboarding tasks apt for role if tasks are defined to map to functions</description>
        <inlineHelpText>When defining a partner contact, use these values to broadly identify the contact&apos;s function. Field used to generate onboarding tasks apt for role if tasks are defined to map to functions</inlineHelpText>
        <label>Role Function</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Partner_Persona</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

Partner Onboarding/objects/Onboarding__c.object
<CustomObject>
    <label>Onboarding Template</label>
    <nameField>
        <label>Onboarding Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partner Onboarding/objects/Onboarding_Tasks__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <description>Provides a short description that appears on the tile.</description>
        <inlineHelpText>Short summary of tasks, such as Forms or Meet the Team.</inlineHelpText>
        <label>Category</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Use this field to capture a description of the action/task pertinent to the tile.</description>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Duration_in_Days__c</fullName>
        <label>Duration (in Days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Onboarding_Plan__c</fullName>
        <label>Onboarding Plan</label>
        <referenceTo>Onboarding__c</referenceTo>
        <relationshipLabel>Onboarding Tasks</relationshipLabel>
        <relationshipName>Onboarding_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Seq__c</fullName>
        <inlineHelpText>Multiple tasks can have the same sequence number if they apply to different audiences.</inlineHelpText>
        <label>Seq #</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Which_roles_is_this_task_for__c</fullName>
        <defaultValue>&quot;All&quot;</defaultValue>
        <inlineHelpText>Select the audience group the task is applicable for and pick a Seq# accordingly. By default actions are applicable to all audience groups in your partner&apos;s hierarchy if one exists</inlineHelpText>
        <label>Which roles is this task for?</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Partner_Persona</valueSetName>
        </valueSet>
    </fields>
    <label>Onboarding Task</label>
    <nameField>
        <displayFormat>OT-{00000}</displayFormat>
        <label>Tasks #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Onboarding Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partner Onboarding/objects/Planned_Onboarding_Tasks__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <label>Assigned To</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Planned_Onboarding_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Duration_in_Days__c</fullName>
        <label>Duration (in Days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Seq__c</fullName>
        <label>Seq #</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TemplateTask__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Template Task</label>
        <referenceTo>Onboarding_Tasks__c</referenceTo>
        <relationshipName>Planned_Onboarding_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Onboarding Task</label>
    <nameField>
        <displayFormat>OT-{00000}</displayFormat>
        <label>Task#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Onboarding Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partner Onboarding/globalValueSets/Partner_Persona.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
        <default>true</default>
        <label>All</label>
    </customValue>
    <customValue>
        <fullName>Technical</fullName>
    </customValue>
    <description>Used to hold the partner contact&apos;s persona / function, enabling the design of on-boarding tasks accordingly. The default is set to &apos;All&apos; and should not be changed</description>
    <masterLabel>Partner Role Function</masterLabel>
</GlobalValueSet>

Partner Onboarding/classes/OnboardingPlanService.cls
public class OnboardingPlanService {
    
    public static void createOnboardingTasks(Map<Id,Id> contactsIDswithTemplateIDs)
    {
        List<Planned_Onboarding_Tasks__c> contactTasks = new List<Planned_Onboarding_Tasks__c>();
        List<Onboarding_Tasks__c> tasksToInsert = [SELECT 
                                                                   Name,
                                                                   Category__c,
                                                                   Description__c,
                                                                   Duration_in_Days__c,
                                                                   Onboarding_Plan__c,
                                                                   Seq__c,
                                                                   Which_roles_is_this_task_for__c
                                                                   FROM Onboarding_Tasks__c
                                                                   WHERE Onboarding_Plan__r.Id IN:contactsIDswithTemplateIDs.values()];
        
        List<Contact> ContactsToUpdate = [SELECT Name,
                                          Onboarding_Plan__c,
                                          Account.Onboarding_Plan__c,
                                          Role_Function__c,
                                          Id
                                          FROM CONTACT
                                          WHERE ID IN :contactsIDswithTemplateIDs.keySet()];
        
        
        for(Contact con : ContactsToUpdate){
            
            if (Schema.sObjectType.Contact.fields.Onboarding_Plan__c.isUpdateable()) {
            	con.Onboarding_Plan__c = con.account.Onboarding_Plan__c;
            }
            
            for(Onboarding_Tasks__c t : tasksToInsert) {
                 
                String role = con.Role_Function__c;
                System.debug('************ROLE IS***********'+role);
                
                if(con.Role_Function__c == null 
                   || t.Which_roles_is_this_task_for__c.contains(role)
                   || t.Which_roles_is_this_task_for__c.contains('All')){
                       Planned_Onboarding_Tasks__c pt = new Planned_Onboarding_Tasks__c();
                       
                       if (Schema.sObjectType.Planned_Onboarding_Tasks__c.fields.Assigned_To__c.isUpdateable()) {
                       		pt.Assigned_To__c = con.Id;    
                       }
                       
                       if (Schema.sObjectType.Planned_Onboarding_Tasks__c.fields.Category__c.isUpdateable()) {
                           pt.Category__c = t.Category__c;
                       }
                       
                       if (Schema.sObjectType.Planned_Onboarding_Tasks__c.fields.Description__c.isUpdateable()) {
                           pt.Description__c = t.Description__c;
                       }
                       
                       if (Schema.sObjectType.Planned_Onboarding_Tasks__c.fields.Duration_in_Days__c.isUpdateable()) {
                           pt.Duration_in_Days__c = t.Duration_in_Days__c;
                       }
                       
                       if (Schema.sObjectType.Planned_Onboarding_Tasks__c.fields.TemplateTask__c.isUpdateable()) {
                           pt.TemplateTask__c = t.Id;
                       }
                       
                       if (Schema.sObjectType.Planned_Onboarding_Tasks__c.fields.Seq__c.isUpdateable()) {
                           pt.Seq__c = t.Seq__c;                             
                       }
                       
                       if (Schema.sObjectType.Planned_Onboarding_Tasks__c.isCreateable()) {
                       	   contactTasks.add(pt);
                       }
                   }                
            }
        }
        
        if (Schema.sObjectType.Planned_Onboarding_Tasks__c.isCreateable()) {
        	if (contactTasks.size() > 0) {
            	insert contactTasks;        
            }
        }
    }
    
    public static void updateContactsWithOndbPlan(Map<Id,Id> accountWithTemplateIDs)
    {
        
        List<Contact> AccountContacts = [SELECT Name,
                                         Onboarding_Plan__c,
                                         Account.Onboarding_Plan__c,
                                         Id
                                         FROM CONTACT
                                         WHERE AccountID IN :accountWithTemplateIDs.keySet()];
        
        
        for(Contact con : AccountContacts){
            con.Onboarding_Plan__c = con.account.Onboarding_Plan__c;
            con.Onboarding_Status__c = 'Not Started';
        }
        
        if (Schema.sObjectType.Contact.isUpdateable()) {
        	update AccountContacts;    
        }
    }      
}