Partner Onboarding/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Onboarding_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Onboarding Template</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Onboarding__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Onboarding__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Partner Onboarding/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Onboarding_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Onboarding Template</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Onboarding__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Onboarding__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Onboarding_Status__c</fullName>
        <inlineHelpText>Holds the current status of the onboarding plan for the contact. Key field to drive business process based on journey status. Use it to trigger notifications, posts, requesting of funds etc.</inlineHelpText>
        <label>Onboarding Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Role_Function__c</fullName>
        <defaultValue>&quot;All&quot;</defaultValue>
        <description>When defining a partner contact, use these values to broadly identify the contact&apos;s function. Field used to generate onboarding tasks apt for role if tasks are defined to map to functions</description>
        <inlineHelpText>When defining a partner contact, use these values to broadly identify the contact&apos;s function. Field used to generate onboarding tasks apt for role if tasks are defined to map to functions</inlineHelpText>
        <label>Role Function</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Partner_Persona</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

Partner Onboarding/objects/Onboarding__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Onboarding Template</label>
    <nameField>
        <label>Onboarding Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partner Onboarding/objects/Onboarding_Tasks__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <description>Provides a short description that appears on the tile.</description>
        <inlineHelpText>Short summary of tasks, such as Forms or Meet the Team.</inlineHelpText>
        <label>Category</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Use this field to capture a description of the action/task pertinent to the tile.</description>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Onboarding_Plan__c</fullName>
        <label>Onboarding Plan</label>
        <referenceTo>Onboarding__c</referenceTo>
        <relationshipLabel>Onboarding Tasks</relationshipLabel>
        <relationshipName>Onboarding_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Seq__c</fullName>
        <inlineHelpText>Multiple tasks can have the same sequence number if they apply to different audiences.</inlineHelpText>
        <label>Seq #</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Onboarding Task</label>
    <nameField>
        <displayFormat>OT-{00000}</displayFormat>
        <label>Tasks #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Onboarding Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partner Onboarding/objects/Planned_Onboarding_Tasks__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <label>Assigned To</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Planned_Onboarding_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seq__c</fullName>
        <label>Seq #</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Onboarding Task</label>
    <nameField>
        <displayFormat>OT-{00000}</displayFormat>
        <label>Task#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Onboarding Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partner Onboarding/globalValueSets/Partner_Persona.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
        <default>true</default>
        <label>All</label>
    </customValue>
    <customValue>
        <fullName>Technical</fullName>
    </customValue>
    <description>Used to hold the partner contact&apos;s persona / function, enabling the design of on-boarding tasks accordingly. The default is set to &apos;All&apos; and should not be changed</description>
    <masterLabel>Partner Role Function</masterLabel>
</GlobalValueSet>

Partner Onboarding/classes/TestOnboardingPlanService.cls
@isTest
public class TestOnboardingPlanService {
    
    public static User createPartnerUser() {
        
        Account a = new Account(name = 'Partner Account');
        insert a;
        
        Contact c = new Contact(LastName = 'PartnerTest', AccountId = a.Id , Role_Function__c = 'All');
        insert c;
        
        User u = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Partner Community User'].Id,
            LastName = 'Test',
            Email = 'test@partneronboarding.com',
            Username = 'test@partneronboarding.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'ptobrd',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ContactId = c.Id
            
        );
        
        insert u;
        
        return u;
    } //End
    
    public static testmethod void updateContactsWithOndbPlan_whenObPlanAddedtoAccount() {
        User partneruser = createPartnerUser();
        
        // Test Setup
        Contact partnerCon = [SELECT NAME, ACCOUNTID FROM CONTACT WHERE ID =:partneruser.ContactId];
        Onboarding__c obplan = new Onboarding__c(Name = 'TEST PLAN', Status__c = 'Active');
        insert obplan;
        Account partnerAccount = [SELECT NAME, 
                                  Onboarding_Plan__c 
                                  FROM ACCOUNT
                                  WHERE ID = :partnerCon.AccountId];
        partnerAccount.Onboarding_Plan__c = obplan.id;
        update partnerAccount;
        
        Map<Id,Id> accountwithtemplateID = new Map<Id,Id>();
        accountwithtemplateID.put(partnerAccount.Id, obplan.id);
        
        //Run test
        Test.startTest();
        
        System.runAs(partneruser){
            OnboardingPlanService.updateContactsWithOndbPlan(accountwithtemplateID);
        }
        
        Test.stopTest();
        
        //Assert
        List<Contact> con = [SELECT Role_Function__c,
                             Onboarding_Plan__c, 
                             ID
                             FROM CONTACT 
                             WHERE ACCOUNTID =:PARTNERACCOUNT.ID];
        System.assertEquals(obplan.id, con[0].Onboarding_Plan__c);
    }
    
    public static testmethod void createOnboardingTasks_forContactsafterOBPlanAssociated(){
        User partneruser = createPartnerUser();
        //Test Setup
        Contact partnerCon = [SELECT NAME, Role_Function__c, ACCOUNTID FROM CONTACT WHERE ID =:partneruser.ContactId];
        
        Onboarding__c obplan = new Onboarding__c(Name = 'TEST PLAN', Status__c = 'Active');
        insert obplan;
        
        Onboarding_Tasks__c otask = new Onboarding_Tasks__c(Category__c = 'Category1',
                                                                                      Description__c = 'Test1',
                                                                                      Onboarding_Plan__c = obplan.Id,
                                                                                      Seq__c = 1);
        insert otask;
        
        Account partnerAccount = [SELECT NAME, 
                                  Onboarding_Plan__c 
                                  FROM ACCOUNT
                                  WHERE ID = :partnerCon.AccountId];
        partnerAccount.Onboarding_Plan__c = obplan.id;
        update partnerAccount;
        
        Map<Id,Id> accountwithtemplateID = new Map<Id,Id>();
        accountwithtemplateID.put(partnerAccount.Id, obplan.id);
 		
        Map<Id,Id> contactwithtemplateID = new Map<Id,Id>();
        contactwithtemplateID.put(partnercon.Id, obplan.id);
        
        // Run Test
        Test.startTest();
        OnboardingPlanService.createOnboardingTasks(contactwithtemplateID);
        Test.stopTest();
        
        // Assert
        List<Planned_Onboarding_Tasks__c> conTasks = [SELECT Category__c, Assigned_To__c
                                                                      FROM Planned_Onboarding_Tasks__c
                                                                      WHERE Assigned_To__c = :partnerCon.Id];
        
        System.assertEquals(2, conTasks.size());
        System.assertEquals('All', partnerCon.Role_Function__c);
       	
    }
    
    public static void defaultOnboardingStatus_WhenOnboardingPlanIsAttachedToNewContact_IsSetToNotStarted() {
        Account a = new Account(Name = 'Test');
        insert a;
        
        Onboarding__c obplan = new Onboarding__c(Name = 'TEST PLAN', Status__c = 'Active');
        insert obplan;
        
        Onboarding_Tasks__c otask = new Onboarding_Tasks__c(Category__c = 'Category1',
                                                                                      Description__c = 'Test1',
                                                                                      Onboarding_Plan__c = obplan.Id,
                                                                                      Seq__c = 1);
        insert otask;
        
        Test.startTest();
        
        Contact c = new Contact(LastName = 'Test', Onboarding_Plan__c = obplan.Id, Onboarding_Status__c = '');
        insert c;
        
        Test.stopTest();
        
        System.assertEquals('Not Started', c.Onboarding_Status__c);
    }
	
    public static void defaultOnboardingStatus_WhenOnboardingPlanIsAttachedToExistingContact_IsSetToNotStarted() {
        Account a = new Account(Name = 'Test');
        insert a;
        
        Onboarding__c obplan = new Onboarding__c(Name = 'TEST PLAN', Status__c = 'Active');
        insert obplan;
        
        Onboarding_Tasks__c otask = new Onboarding_Tasks__c(Category__c = 'Category1',
                                                                                            Description__c = 'Test1',
                                                                                            Onboarding_Plan__c = obplan.Id,
                                                                                            Seq__c = 1);
        
        Contact c = new Contact(LastName = 'Test', Onboarding_Status__c = '');
        insert c;
        
        insert otask;
        
        Test.startTest();
        
        c.Onboarding_Plan__c = obplan.Id;
        update c;
        
        Test.stopTest();
        
        System.assertEquals('Not Started', c.Onboarding_Status__c);
    } 
}