Partner Onboarding/objects/Onboarding_Tasks__c.object
<CustomObject>
    <fields>
        <fullName>Action_Params__c</fullName>
        <description>Set of params depending upon action type
For Link set this to a URL (HTTPS supported)
For Create record set this to the object name
For Navigate To Object set this value to the Id of the object (relative URLs should be added without a &apos;/&apos; prefix)
For Video set this to the embeddable video link</description>
        <inlineHelpText>Based on Action Type, insert an HTTPS external URL or embeddable video link, record ID, or object name</inlineHelpText>
        <label>Action Params</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Action_Type__c</fullName>
        <label>Action Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Link</fullName>
                </value>
                <value>
                    <fullName>Create Record</fullName>
                </value>
                <value>
                    <fullName>Display Video</fullName>
                </value>
                <value>
                    <fullName>Navigate to Object</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Button_Label__c</fullName>
        <description>Can be used to control the text that appears on the button for each tile. Determines the text that appears as the button label in the community. Partner Users could click into the button to undertake / review the tile.</description>
        <label>Button Label</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>Provides a short description that appears on the tile.</description>
        <inlineHelpText>Short summary of tasks, such as Forms or Meet the Team.</inlineHelpText>
        <label>Category</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Complete_Task_When_Action_clicked__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Controls if clicking into a tile should be deemed as tile action completion.</description>
        <inlineHelpText>Action is considered complete after a member clicks the tile.</inlineHelpText>
        <label>Complete Task When Action clicked?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Use this field to capture a description of the action/task pertinent to the tile.</description>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Image_Name__c</fullName>
        <inlineHelpText>Complete URL of the tile image</inlineHelpText>
        <label>Image Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seq__c</fullName>
        <inlineHelpText>Multiple tasks can have the same sequence number if they apply to different audiences.</inlineHelpText>
        <label>Seq #</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Onboarding Task</label>
    <nameField>
        <displayFormat>OT-{00000}</displayFormat>
        <label>Tasks #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Onboarding Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partner Onboarding/objects/Planned_Onboarding_Tasks__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <label>Assigned To</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Planned_Onboarding_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Computed_Status__c</fullName>
        <formula>IF(
  today() &gt; Task_Due_Date__c &amp;&amp; NOT(ISPICKVAL(Status__c, &apos;Completed&apos;)), 
  &quot;Overdue&quot;,
  IF(
    Task_Due_Date__c == today() &amp;&amp; NOT(ISPICKVAL(Status__c, &apos;Completed&apos;)), 
    &quot;Due&quot;,
    TEXT(Status__c)
  )
)</formula>
        <label>Computed Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seq__c</fullName>
        <label>Seq #</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TemplateTask__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Template Task</label>
        <referenceTo>Onboarding_Tasks__c</referenceTo>
        <relationshipName>Planned_Onboarding_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Onboarding Task</label>
    <nameField>
        <displayFormat>OT-{00000}</displayFormat>
        <label>Task#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Onboarding Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partner Onboarding/classes/OnboardingService.cls
public with sharing class OnboardingService {
	
    @AuraEnabled
    public static List<Planned_Onboarding_Tasks__c> replaceParams(List<Planned_Onboarding_Tasks__c> tasks, User u) {
        for (Planned_Onboarding_Tasks__c task : tasks) {
            if (task.TemplateTask__r != null) {
                if (task.TemplateTask__r.Action_Params__c != null) {
                    if (task.TemplateTask__r.Action_Params__c.contains('{! User.Id }')) {
                        task.TemplateTask__r.Action_Params__c = task.TemplateTask__r.Action_Params__c.replace('{! User.Id }', u.Id);
                    }   
                }    
            }
            
        }
        
        return tasks;
    }
    
    public static Boolean checkFieldAccessibility() {
        return (
            Schema.sObjectType.Planned_Onboarding_Tasks__c.isAccessible() &&
            Schema.sObjectType.Planned_Onboarding_Tasks__c.fields.TemplateTask__c.isAccessible() &&
			Schema.sObjectType.Planned_Onboarding_Tasks__c.fields.Computed_Status__c.isAccessible() &&
            Schema.sObjectType.Onboarding_Tasks__c.fields.Category__c.isAccessible() &&
            Schema.sObjectType.Onboarding_Tasks__c.fields.Description__c.isAccessible() &&
            Schema.sObjectType.Onboarding_Tasks__c.fields.Image_Name__c.isAccessible() &&
            Schema.sObjectType.Onboarding_Tasks__c.fields.Button_Label__c.isAccessible() &&
            Schema.sObjectType.Onboarding_Tasks__c.fields.Seq__c.isAccessible() &&
            Schema.sObjectType.Onboarding_Tasks__c.fields.Action_Type__c.isAccessible() &&
            Schema.sObjectType.Onboarding_Tasks__c.fields.Action_Params__c.isAccessible() &&
            Schema.sObjectType.Onboarding_Tasks__c.fields.Complete_Task_When_Action_clicked__c.isAccessible()
        );
    }
    
    @AuraEnabled
    public static List<Planned_Onboarding_Tasks__c> getTasksForContact() {
        
        List<Planned_Onboarding_Tasks__c> results 
            = new List<Planned_Onboarding_Tasks__c>();
        
        if (checkFieldAccessibility()) {
            List<User> users = [SELECT Id, ContactId FROM User WHERE Id = :UserInfo.getUserId()];
            if (users.size() > 0) {
                results = [
                    SELECT 
                    Id, 
                    TemplateTask__r.Category__c, 
                    TemplateTask__r.Description__c,
                    Computed_Status__c,
                    TemplateTask__r.Image_Name__c,
                    TemplateTask__r.Button_Label__c,
                    TemplateTask__r.Seq__c,
                    TemplateTask__r.Action_Type__c,
                    TemplateTask__r.Action_Params__c,
                    TemplateTask__r.Complete_Task_When_Action_clicked__c
                    FROM 
                    Planned_Onboarding_Tasks__c
                    WHERE 
                    Assigned_To__c = :users.get(0).ContactId
                    ORDER BY Seq__c ASC ];
                
                results = replaceParams(results, users[0]);
            }    
        }
            
        return results;
    }
    
    @AuraEnabled
    public static void completeTask(Id taskId) {
        if (Schema.sObjectType.Planned_Onboarding_Tasks__c.isUpdateable()) {
            if (Schema.sObjectType.Planned_Onboarding_Tasks__c.fields.Status__c.isUpdateable()) {
                if (taskId != null) {
                    Planned_Onboarding_Tasks__c task = new Planned_Onboarding_Tasks__c(
                        Id = taskId, 
                        Status__c = 'Completed');
                    update task;    
                }   
            }
        }
    }
    
    /**
	  * Finds the Id of the channel manager of the curren user
		* returns null if the user is not a portal user
		* @return Id of channel manager
	*/
	@TestVisible
	private static Id getChannelManager() {
		User u = [
		SELECT Contact.Account.OwnerId
		FROM User
		WHERE Id = :UserInfo.getUserId()];

		if (u.Contact != null) {
			if (u.Contact.Account != null) {
				return u.Contact.Account.OwnerId;
			}
		}

		return null;
	}
    
    @AuraEnabled
    public static ConnectApi.UserProfile getUserProfile() {
        return ConnectApi.UserProfiles.getUserProfile(Network.getNetworkId(), getChannelManager());
    }
     
    @AuraEnabled
    public static String getUserDetails() {
        return UserInfo.getFirstName();
    }
}